// Dữ liệu phim mẫu
export const moviesData = [
  {
    id: 1,
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    genre: ['Action', 'Crime', 'Drama'],
    rating: 9.0,
    year: 2008,
    duration: '152 min',
    thumbnail: 'https://via.placeholder.com/300x450/1A1A1A/FFFFFF?text=The+Dark+Knight',
    banner: 'https://via.placeholder.com/800x400/1A1A1A/FFFFFF?text=The+Dark+Knight',
  },
  {
    id: 2,
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    rating: 8.8,
    year: 2010,
    duration: '148 min',
    thumbnail: 'https://via.placeholder.com/300x450/1A1A1A/FFFFFF?text=Inception',
    banner: 'https://via.placeholder.com/800x400/1A1A1A/FFFFFF?text=Inception',
  },
  {
    id: 3,
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 8.6,
    year: 2014,
    duration: '169 min',
    thumbnail: 'https://via.placeholder.com/300x450/1A1A1A/FFFFFF?text=Interstellar',
    banner: 'https://via.placeholder.com/800x400/1A1A1A/FFFFFF?text=Interstellar',
  },
  {
    id: 4,
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genre: ['Action', 'Sci-Fi'],
    rating: 8.7,
    year: 1999,
    duration: '136 min',
    thumbnail: 'https://via.placeholder.com/300x450/1A1A1A/FFFFFF?text=The+Matrix',
    banner: 'https://via.placeholder.com/800x400/1A1A1A/FFFFFF?text=The+Matrix',
  },
  {
    id: 5,
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    genre: ['Crime', 'Drama'],
    rating: 8.9,
    year: 1994,
    duration: '154 min',
    thumbnail: 'https://via.placeholder.com/300x450/1A1A1A/FFFFFF?text=Pulp+Fiction',
    banner: 'https://via.placeholder.com/800x400/1A1A1A/FFFFFF?text=Pulp+Fiction',
  },
];
